apiVersion: v1
kind: Pod
metadata:
  name: podtest
  namespace: default
spec:
  restartPolicy: OnFailure
  containers:
    - name: podtest
      image: "nginx"
      extendedResourceClaims: 
      - "erctest"
